name: config_test
description: Test package
publish_to: none

environment:
  sdk: ^3.5.0
  flutter: ">=3.27.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_inset_shadow: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.6.0
  test: ^1.20.0
  genuis:
    path: ../../
